name: redgate-anonymize-example
 
schedules:
- cron: 0 2 * * * # cron syntax for 2am daily
  branches:
    include: 
    - main
  displayName: 2am daily # friendly name given to a specific schedule

parameters:
- name: serverinstance
  default: WIN2016
- name: databaseName
  default: Eastwind

stages:
  - stage: Anonymize  
    displayName: Anonymize
    jobs:
    - job: ${{parameters.databaseName}}
      displayName: Anonymize ${{parameters.databaseName}}

      steps:
      - script: 'anonymize mask --database-engine SqlServer --connection-string "Server=WIN2016; Database=Eastwind; Integrated Security=true; TrustServerCertificate=true" --masking-file config\masking.json --options-file config\options.json'
        displayName: 'Command Line Script'