name: redgate-subset-image-example
 
schedules:
- cron: 0 3 * * * # cron syntax for 3am daily
  branches:
    include: 
    - main
  displayName: 3am daily # friendly name given to a specific schedule

parameters:
- name: serverinstance
  default: WIN2016
- name: databaseName
  default: Eastwind

stages:
  - stage: Subset  
    displayName: Subset
    jobs:
    - job: ${{parameters.databaseName}}
      displayName: Subset ${{parameters.databaseName}}

      steps:
      - powershell: |
          Write-Output "To do: Restore a backup"
        displayName: 'Restore backup'
      - powershell: |
          Write-Output "To do: Run DBCC CLONE DB"
        displayName: 'Create target for subset'
      - powershell: |
          Write-Output "To do: Run subset"
        displayName: 'Run subset'
      - powershell: |
          Write-Output "To do: Backup target DB"
        displayName: 'Backup target'
      - powershell: |
          Write-Output "To do: Delete staging databases"
        displayName: 'Clean up'

  - stage: CreateImage  
    displayName: Create Image
    jobs:
    - job: ${{parameters.databaseName}}
      displayName: Create rgclone image for ${{parameters.databaseName}}

      steps:
      - powershell: |
          Write-Output "To do: Copy backup to fileshare"
        displayName: 'Copy backup to file share'
      - powershell: |
          Write-Output "To do: Create rgclone data image"
        displayName: 'Create rgclone data image'